name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:

  build_hello-world:

    defaults:
      run:
        working-directory: rust/hello-world

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Lint  
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build release
        run: cargo build --release

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-world
          path: |
            rust/hello-world/target/release/hello-world

