name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_hello-world:

    defaults:
      run:
        working-directory: rust/hello-world

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint  
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --al
