name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint  
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
        working-directory: rust/hello-world

      - name: Test
        run: |
          cargo check
          cargo test --all
         working-directory: rust/hello-world

      - name: Build
        run: |
          cargo build --release
        working-directory: rust/hello-world

      - name: Run
        run: |
          cargo run
        working-directory: rust/hello-world
